id = "mojo"
name = "Mojo"
description = "Mojo support."
version = "0.0.2"
schema_version = 1
authors = ["Ayush Shukla <ayush@shuklaayu.sh>"]
repository = "https://github.com/emillma/zed-mojo"

[grammars.mojo]
repository = "https://github.com/emillma/tree-sitter-mojo"
commit = "3783d6ceed2e28f10bd017bd53c438e79e02208c"

[language_servers.mojo-lsp]
name = "mojo-lsp"
language = "Mojo"

[debug_adapters.mojo-lldb]
schema_path = "debug_adapter_schemas/mojo-lldb.json"
