id = "mojo"
name = "Mojo"
description = "Mojo support."
version = "0.0.1"
schema_version = 1
authors = ["Ayush Shukla <ayush@shuklaayu.sh>"]
repository = "https://github.com/shuklaayush/zed-mojo"

[grammars.mojo]
repository = "https://github.com/shuklaayush/tree-sitter-mojo"
commit = "88e94a5aba70aa6d20e06fb3c9e6d18f1a61d615"

[language_servers.mojo-lsp]
name = "mojo-lsp"
language = "Mojo"

[debug_adapters.mojo-lldb]
schema_path = "debug_adapter_schemas/mojo-lldb.json"
